### ISSUE TITLE
Mismatched Node requirements

### ISSUE THREAD

**Issue by nexstar-tom-j-nowell** [alleyinteractive/byline-manager#237]
### Description of the bug

bylines manager requires Node v16, but its dependencies require Node 18/20!

### Steps To Reproduce

```
❯ npm ci
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'postcss-focus@7.0.0',
npm WARN EBADENGINE   required: { node: '^18.0.0 || >=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.20.0', npm: '8.19.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'postcss-import@16.0.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.20.0', npm: '8.19.4' }
npm WARN EBADENGINE }
```

### Acceptance Criteria

- Update to node 20 and npm 10
- Update packages to latest version, except WordPress dependencies, which should be pinned to the 6.4 version
- Bonus Points: Migrate to Alley's build system/ESLint config/etc.

### Additional Information

I used `nvm use` to make sure I had the appropriate Node version installed, then ran `npm ci` and saw the issue.

I would recommend upgrading to Node 20 as that's what core uses, 18 at a minimum

**Comment by kaitlinbolling** [comment]
Updated in version 2.0.5.
