### ISSUE TITLE
stylelint runs on composer vendor folder assets

### ISSUE THREAD

**Issue by nexstar-tom-j-nowell** [alleyinteractive/byline-manager#238]
### Description of the bug

When building and linting stylelint is incorrectly ran on files in composer dependencies, generating thousands of results

### Steps To Reproduce

```sh
nvm use
npm install
npm run build
```

### Additional Information

I'd suggest ignoring the vendor folder when linting CSS

**Comment by renatonascalves** [comment]
Fixed at #240
