### ISSUE TITLE
Update breaks adding new bylines

### ISSUE THREAD

**Issue by arueden** [alleyinteractive/byline-manager#259]
### Description of the bug

I updated to to the latest version of this plugin (from 0.2.4 to 0.2.5). Doing manual testing, I realized the bylines weren't saving at all. Existing bylines stay put, but new ones do not save.

### Steps To Reproduce

1. Update to v0.2.5
2. Create a new post or edit an existing post
3. Add a new byline value
4. Update
5. New byline does not appear
6. Edit the page again; there is nothing in the field

### Additional Information

I confirmed this bug by downgrading back to 0.2.4. Bylines work as expected again.

**Comment by james-tyner** [comment]
We are also having this issue on 0.2.5!

**Comment by mboynes** [comment]
Thanks for letting us know! We found the culprits, will ship 0.2.6 right after #261 is merged.

**Comment by mboynes** [comment]
Er, rather, 0.2.7 will fix the issues. Sorry for the confusion!

**Comment by kevinfodness** [comment]
I just shipped v0.2.7. @arueden can you update and confirm the fix on your end?

**Comment by arueden** [comment]
Yes, I tested the new version and the problem is gone!

**Comment by mboynes** [comment]
Thanks for confirming @arueden!
