### ISSUE TITLE
Byline Manager is broken when using the Classic Editor

### ISSUE THREAD

**Issue by jakewrfoster** [alleyinteractive/byline-manager#273]
### Description of the bug

Byline Manager is broken in the Classic Editor in version 0.2.4 and later (tested up to 0.2.7 at the time of writing).

### Steps To Reproduce

1. Activate Byline Manager at version 0.2.4 or later
2. Create or edit a post in the classic editor.
3. Note that Byline Manager's meta box appears in the editor but it is empty.

**Comment by scottnelle** [comment]
Updated the issue with some specifics. There's a type error in the byline manager JS, but I'm testing with built versions of the plugin so the specific error is obscured. Someone who's set up to test dev versions of the plugin could likely pinpoint the error pretty quickly.

**Comment by renatonascalves** [comment]
I can confirm the error. But there are more stuff broken here. Stylelint has `1960 problems (1960 errors, 0 warnings)`.

**Comment by renatonascalves** [comment]
Just noticed #240 will resolve the linting issue.
