### ISSUE TITLE
Replace Buddy with GitHub Actions

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/byline-manager#365]
## Description

Upgrading the project from Buddy to GitHub actions will ensure parity with other Alley projects, reduce costs, and allow leveraging 'shared' common workflows or actions.

## Acceptance Criteria

- All CI/CD pipelines (eg. PR tests or deployment) are replaced by equivalent GitHub actions
- Any secrets are recreated or moved to GitHub secrets (environment or otherwise)
- Buddy disabled for the project

**Comment by benpbolton** [comment]
@kevinfodness this work seems to be accomplished already - perhaps I'm missing something?

![Image](https://github.com/user-attachments/assets/b5d00ee5-5726-4465-ae79-1a77fcb887f0)

**Comment by benpbolton** [comment]
This work seems to be completed already.
